services:
  app:
    build: .
    container_name: shopping_app
    ports:
      - "8501:8501"   # Streamlit
      - "8000:8000"   # FastAPI
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  db:
    image: postgres:15
    container_name: shopping_db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: shopping_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  ollama_data:
  redis_data:
