from enum import Enum

class ProductCategoryEnum(str, Enum):
    SAUCES = "sauces"
    SPICES_CONDIMENTS = "spices_condiments"
    DAIRY = "dairy"
    BAKERY = "bakery"
    MEAT_POULTRY = "meat_poultry"
    SEAFOOD = "seafood"
    FRUITS = "fruits"
    VEGETABLES = "vegetables"
    BEVERAGES = "beverages"
    SNACKS = "snacks"
    FROZEN_FOODS = "frozen_foods"
    CANNED_GOODS = "canned_goods"
    CONDIMENTS_SAUCES = "condiments_sauces"
    GRAINS_PASTA = "grains_pasta"
    SWEETS_DESSERTS = "sweets_desserts"
    SPICES_HERBS = "spices_herbs"
    OILS_FATS = "oils_fats"
    BABY_FOOD = "baby_food"
    HEALTH_WELLNESS = "health_wellness"
    ORGANIC = "organic"
    CONVENIENCE_FOODS = "convenience_foods"
    INTERNATIONAL_FOODS = "international_foods"
